services:
  sdn-test:
    image: sdn
    ports:
      - 7681:7681
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/net/tun

